[project]
name = "raksh"
version = "1.0.0"
readme = "README.md"
authors = [
    {name="Malakai Spann", email="MalakaiSpann@gmail.com"}
]

description = "Opinionated types and logic for handling operation results in Python"
requires-python = ">=3.9"
license = {file = "LICENSE"}
classifiers = [
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Software Development',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
]
dependencies = []

[project.urls]
Repository = "https://github.com/malakaispann/raksh"


[dependency-groups]
dev = [
	{include-group = "format"},
  	{include-group = "test"},
	{include-group = "docs"}
]
docs = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.0.0",
    "mike>=2.1.0",
    "mkdocs-simple-hooks>=0.1.5",
    "mkdocstrings[python]>=0.20.0",
]
format = [
    "black>=25.11.0",
    "pylint>=3.3.9",
    "pylint-per-file-ignores>=2.0.3",
]
release = [
    "python-semantic-release>=10.5.2",
]
test = [
    "pytest>=8.4.2",
    "pytest-random-order>=1.2.0",
]


[build-system]
requires = ["uv_build>=0.9.14,<0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "-rpfs --quiet --random-order-bucket=class"
testpaths = [
    "src/tests"
]
pythonpath = [
    "src"
]

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
commit_parser = "conventional"

build_command = """
    uv lock --upgrade-package "$PACKAGE_NAME"
    git add uv.lock
    uv build
"""

[tool.semantic_release.branches.main]
match = "(develop)"
pre-release = false

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*", "README.md", "docs/CHANGELOG.md"]
upload_to_vcs_release = true

[tool.semantic_release.changelog]
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
    '''build\((?!deps\): .+)''',
    '''Initial [Cc]ommit.*''',
]

[tool.semantic_release.changelog.default_templates]
changelog_file = "docs/CHANGELOG.md"
output_format = "md"

[tool.uv.build-backend]
module-name = "raksh"
module-root = "src"


