name: Check code quality

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format check
        run: make format-check

  lint:
    name: Execute Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint check
        run: make lint-check

  test:
    name: Execute Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: make test